### ISSUE TITLE
如何使用的问题

### ISSUE THREAD

**Issue by RoryJYL** [alexayan/garbage-classification-data#1]
请问是直接输入那个npm命令就可以吗，我在win10环境下输入后有这些警告信息
npm WARN saveError ENOENT: no such file or directory, open 'A:\data\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'A:\data\package.json'
npm WARN data No description
npm WARN data No repository field.
npm WARN data No README data
npm WARN data No license field.

请问是我理解错了还是我的环境配置有问题

**Comment by alexayan** [comment]
项目目录中的 garbage.json, garbage.csv 已包含所有数据，下载到你的机器上就可以直接使用

**Comment by RoryJYL** [comment]
好的 谢谢
