### ISSUE TITLE
垃圾目录

### ISSUE THREAD

**Issue by liwen-tj** [alexayan/garbage-classification-data#2]
你的垃圾目录对应有问题吧，1，2，3，4对应的垃圾类别写的不对

**Comment by alexayan** [comment]
能举个例子吗

**Comment by liwen-tj** [comment]
我看的是这个文件garbage-classification-data/datasource/github_jihongboo/data.json，你的garbage.csv文件没问题。

**Comment by alexayan** [comment]
不同数据来源有不同的类型定义，但都会转换本项目文档中所定义的类型
