### ISSUE TITLE
楼主数据从哪儿来的？

### ISSUE THREAD

**Issue by elarity** [alexayan/garbage-classification-data#5]
楼主数据从哪儿来的？是自己收集的吗？因为我没有看到官方出这些数据类目数据

**Comment by alexayan** [comment]
目前有两个数据源：
1. http://trash.lhsr.cn/sites/feiguan/trashTypes_2/TrashQuery_h5.aspx
2. https://github.com/jihongboo/wast_sortting_helper_wechat

**Comment by elarity** [comment]
👍👍👍 我一直以为是你自己每天收集提交！
