### ISSUE TITLE
category拼写错误

### ISSUE THREAD

**Issue by Gsllchb** [alexayan/garbage-classification-data#6]
感谢你提供如此好用的垃圾分类数据库！
但是有个小问题：categ**or**y拼写错误，你写的是`categroy`。
在我从你提供的sqlite数据库中导出数据时，报错提示列`category`不存在，排查发现实际库中列名为`categroy`。

**Comment by alexayan** [comment]
感谢使用，已经统一拼写为 `categroy`。

**Comment by ixiaogangwyg1** [comment]
我也发现拼写问题了，应该是 category 吧😂

**Comment by alexayan** [comment]
> 我也发现拼写问题了，应该是 category 吧😂

已重新修正 :-)
